env: "local" #local, dev, prod
storage:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "1"
  dbname: "users"
http_server:
  address: "localhost:8080"
  timeout: "4s"
  idle_timeout: "60s"